name: Release
on:
  pull_request:
  push:

jobs:
  gorelease:
    name: Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      -
        name: Checkout Code
        uses: actions/checkout@v2
      -
        name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
